### ISSUE TITLE
basic documentation about how to use the examples

### ISSUE THREAD

**Issue by StefanL38** [yoursunny/WifiEspNow#11]
Hi yoursunny,

thank you very very much for this library. This looks promising. Though I'm unsecure how to use the examples.

Do I conclude right that for using the broadcast example each member of the ESP-NOW-mesh must run the exact same [EspNowBroadcast.ino](https://github.com/yoursunny/WifiEspNow/blob/master/examples/EspNowBroadcast/EspNowBroadcast.ino) with no modifications?

Do I conclude right that for the [EspNowUnicast.ino](https://github.com/yoursunny/WifiEspNow/blob/master/examples/EspNowUnicast/EspNowUnicast.ino)  example   each  file must be adapted to have the **receivers**\-MAC-Adress 

configured in the EspNowBroadcast.ino -file in variable 

```
static uint8_t PEER[]{0x5E, 0xCF, 0x7F, 0x90, 0xFA, 0xE8};
```

If so some additional code to determine the MAC-adresses would be useful.

You have prepared the documentation for use with doxygen but there seems to be nothing into the documentation yet.

Never used doxygen before. If you can post to a very detailed documentation how to use doxygen I can contribute with writing some documentation how to use your library. If this docygen-manual is not detailed enough to make work with it abreeze I prefer a single PDF-file as documentation.

best regards Stefan

**Comment by yoursunny** [comment]
I have added some instructions at the top of each example, and adjusted Doxygen configuration to include these in the output.
If you want to write additional documentation, you can post them on your blog and I'll link to them.
