### ISSUE TITLE
restructering folder-structure to enable the use of add-ZIP-library  of the Arduino-IDE

### ISSUE THREAD

**Issue by StefanL38** [yoursunny/WifiEspNow#12]
Hi yoursunny,

I donwloaded your WifiEspNow-library and compiled and tested successfully EspNowBroadcast.ino-example

after downloading the code as a zipfile WifiEspNow-master.zip and unzipping it and analysed the strucure of the folders and files

it is well sorted but does not match the structure needed to use the add-zip-library function of the arduino-IDE

the \*.h and \*.cpp-file has to be in a folder that has the name of the \*.h-file

For using the add-zip-library-function the structure must be

C:\\Users\\Stefan\\Documents\\Arduino\\libraries\\WifiEspNow\\WifiEspNow.h

C:\\Users\\Stefan\\Documents\\Arduino\\libraries\\WifiEspNowBroadcast\\WifiEspNowBroadcast.h

in general:

 ....libraries\\**WifiEspNow**\\WifiEspNow.h

 ....libraries\\**WifiEspNowBroadcast**\\WifiEspNowBroadcast.h

same principle for the examples there has to be a sub-folder below WifiEspNowBroadcast named "examples" 

and inside the examples-folder there must be a folder with the name of the sketch and the \*.ino-file is then inside this folder

.....Arduino\\libraries\\WifiEspNowBroadcast\\examples\\**EspNowBroadcast**\\EspNowBroadcast.ino

If the folder-structure is roganised like this the examples show up under the

file - examples-menu of the Arduino-IDE

So what do you think about re-structering in this way to make it easier to use?

May I suggest an additional thing. IMHO names of example-sketches should include the word "demo" so a file-search with keywords like "ESP" "Demo" \*.ino would be quite specific to find it.

**Comment by yoursunny** [comment]
All my libraries should be installed using **git**, not as ZIP archives.
I have added installation steps in `README.md`.

Having `*.h` in the library root folder is the convention of Arduino 1.0.x.
I'm publishing as 1.5.x+-only libraries, where the source code resides in the `src` folder.
See [Arduino library specification](https://arduino.github.io/arduino-cli/library-specification/#layout-of-folders-and-files).
