### ISSUE TITLE
modifying the EspNowBroadcast.ino-example to deliver output you just can copy & paste  into your code that is based on the EspNowUniCast-example

### ISSUE THREAD

**Issue by StefanL38** [yoursunny/WifiEspNow#13]
Hi yoursunny,

I want to make another suggestion:

the EspNowBroadcast.ino-example prints out the mac-adress of the recipients in standard hexadecimal format

```
Recipients: 2E:3A:E8:22:62:30
```

How about adding serial-output that prints out a line of code 

```
static uint8_t PEER[]{0x2E, 0x3A, 0xE8, 0x22, 0x62, 0x30};
```

which is ready for copy & paste into the code to specify the users recipients,

because the line has the actual recipients MAC-Adress?

best regards Stefan

**Comment by yoursunny** [comment]
I don't see why EspNowBroadcast needs to output information for EspNowUnicast example.
However, I added a few lines to EspNowUnicast example to print the device's own MAC address in a copy-able format.
