### ISSUE TITLE
PlatformIO compile receiver not work.

### ISSUE THREAD

**Issue by macauhome** [yoursunny/WifiEspNow#16]
Hi, I use vscode with platformIO to compile and upload the samples to two ESP32 boards, call the receiver and sender, the receive callback function not work, there without any received msg show,but if compile and upload with Arduino IDE, those two components are work well, thanks.

Enviroment :
windows 10 
vscode version: 1.63.2
platformIO extension
esp32 board: NodeMCU-32S

**Comment by yoursunny** [comment]
It's probably caused by different https://github.com/espressif/arduino-esp32 versions.
Have a look at https://github.com/yoursunny/esp32cam/issues/23#issuecomment-1046120261 on how to make PlatformIO select arduino-esp32 v2.0.2.
