### ISSUE TITLE
ota update 

### ISSUE THREAD

**Issue by mrdsn3** [yoursunny/WifiEspNow#17]
can we transfer file with espnow ? is any way to ota update ?  plz give me refrense or example if there any avillable

**Comment by yoursunny** [comment]
ESP-NOW is a low-level datagram transmission protocol.
It is possible to design a file transfer or OTA update protocol on top of it.
However, it probably would not work well, and you basically need to reinvent TCP-like reliability and congestion control.
Hence, it is out of scope for this library.
