### ISSUE TITLE
how to send any kind of data

### ISSUE THREAD

**Issue by SurenBono** [yoursunny/WifiEspNow#20]
It seem to work with the easier broadcast mode than the unicast mode..but how to send any kind of data..I'm planning to send processed neo-6m redundant gps clock data to multiple recipients to output on led matrices..can't figure out how to send int a;a++;serial.println( a) to the recipients..please advise..

**Comment by yoursunny** [comment]
You can transmit a datagram with `.send()` method.

**Comment by SurenBono** [comment]
..ok ..kool!
