### ISSUE TITLE
ESPNow issues with Deep Sleep

### ISSUE THREAD

**Issue by SrikanthBala** [yoursunny/WifiEspNow#4]
I am using a ESP32 Dev Module with the Arduino IDE (1.8.5) with ESP32 core (downloaded from Boards manager)
I am aiming to make a peer to peer connectivity between two ESP32 using ESPNow
I am using a WifiESPNow library
I am using their Unicast example with a hardcoded Peer address, giving each code the partners AP MAcID

The code works perfectly and I pick up every transmission.

However I need to send only about 4-5 transmissions a minute and want to deep sleep in between as it is going to be LiPo battery operated (I will make a standalone ESP32 module for that)

I soon realised that initializing ESPNow once and then entering light sleep (or deep sleep) doesn't work and I need to re-initalize it on every cycle. (I thought it should work with light sleep without re-initializing and this much power is OK by me). As I am basically going to do the entire process of setting up ESPNow again each time, it made sense to use deep sleep instead.

Deep sleep on one of the nodes works well. It sleeps, gets up, waits for a transmission receipt or max for 250 ms and then prints the message and goes to sleep again. This also synchronises the two ESP's once a message is reached as it sends a message and goes to sleep immediately.

However using this method on both nodes, I pick up only one in every 50 or 60 messages and the rest are lost.
Any ideas on how this may be done so that at least 3-4 messages are picked up every second by both ESP's ?

Code is attached. 
[EspNowUnicastDeepSleep.txt](https://github.com/yoursunny/WifiEspNow/files/2615463/EspNowUnicastDeepSleep.txt)

Thanks

**Comment by yoursunny** [comment]
The attached code has lots of unexecuted junk (everything starting from InitESPNow are unnecessary). Please follow [https://stackoverflow.com/help/mcve](MCVE guidelines) next time you report a bug (to this and any other project).

This snippet is problematic:
```
  unsigned long tim = millis() ;
  while((!flgMsgRecd) && ((tim-millis())<250)) ;
  flgMsgRecd = false ;
  int len = snprintf(s, sizeof(s), "%s with Mac Id %s at %lu %d",msg, WiFi.softAPmacAddress().c_str(), millis(),rstcnt++);
  WifiEspNow.send(PEER, reinterpret_cast<const uint8_t*>(s), sizeof(s));

  esp_sleep_enable_timer_wakeup(300000);
  esp_deep_sleep_start();
```
1. Wait 250ms for an incoming message.
2. Transmit a message.
3. Sleep for 5 minutes.

Observations:
* Nobody would transmit first. Even if two nodes wake up at almost but not exactly the same time, normally only one could receive a message.
* ESP-NOW is best-effort delivery. It has acknowledgement `WifiEspNow.getSendStatus()` but not automated retransmission. The app is not doing retransmission.
* Wake period is a lot shorter than sleep period. If sleep timer is a little bit off, the two node would never wake up at the same time, and thus no communication could happen.

The following paper may be related:
> Oliver Hahm, Emmanuel Baccelli, Thomas Schmidt, Matthias Waehlisch, Cédric Adjih. A Named Data Network Approach to Energy Efficiency in IoT. IEEE GLOBECOM Workshop on Named Data Networking for Challenged Communication Environments, Dec 2016, Washington DC, United States. <hal-01369698>

**Comment by SrikanthBala** [comment]
Thank you for your prompt reply.
1. True. A lot of unnecessary junk was sent with the code. I was trying various things to get it to work and the junk was not trimmed off. And yes I have now gone through the MCVE guidelines. Thanks for that. I try to adhere to them in the future

2. I went thru your comments and had in the meanwhile found errors in my code which I will correct. Hopefully I will get it right soon.

3. I have yet to go through the reference paper you sent. 

Will report back . Thanks again

**Comment by SrikanthBala** [comment]
One question regarding the code :
Will the line :
 ok = WifiEspNow.addPeer(PEER); 

try to write the Mac ID and other details about the peer to EEPROM or Flash on every reset ?
That would markedly reduce life of the device as I am resetting every 300 ms

Is it required if the pairing has already been done once ? Should I check to see if pairing exists and only then do this ? If so how ?

Thanks

**Comment by yoursunny** [comment]
> Will the line `ok = WifiEspNow.addPeer(PEER);` try to write the Mac ID and other details about the peer to EEPROM or Flash on every reset ?

I believe **no**, because [ESP-IDF docs](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_now.html#add-paired-device) does not mention persistence of the pairing.
