### ISSUE TITLE
What can I do with this library?

### ISSUE THREAD

**Issue by asjdf** [yoursunny/WifiEspNow#7]

**Comment by sfranzyshen** [comment]
[esp-now user guide](https://www.espressif.com/sites/default/files/documentation/esp-now_user_guide_en.pdf)

1.1. Overview
ESP-NOW is a fast, connectionless communication technology featuring short packet
transmission. ESP-NOW is ideal for smart lights, remote control devices, sensors and other
applications. ESP-NOW applies the IEEE802.11 Action Vendor frame technology, along with the IE
function developed by Espressif, and CCMP encryption technology, realizing a secure,
connectionless communication solution.

It is a proprietary (only ESPs that I know of) connectionless wifi (does not work with other wifi protocols) communication solution. You can exchange information between two (or more) ESPs without making any sort of connection ...

**Comment by sfranzyshen** [comment]
Actually, there is work underway to use this protocol from Linux ...
https://github.com/thomasfla/Linux-ESPNOW/
